[package]
name = "zeitlupius"
version = "0.1.0"
edition = "2026"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
crossterm = "0.29.0"
csv = "1.4.0"
fd-lock = "4.0.4"
jiff = { version = "0.2.24", features = ["serde"] }
ratatui = "0.30.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"

[dev-dependencies]
assert_cmd = "2.2.1"
predicates = "3.1.4"
tempfile = "3.27.0"

[lib]
name = "zeitlupius"
path = "src/lib.rs"

[[bin]]
name = "zeitlupius"
path = "src/main.rs"